# Generated by Django 4.0.3 on 2022-04-02 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdCikk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=255, verbose_name='cím')),
                ('dokumentum', models.FileField(blank=True, upload_to='', verbose_name='dokumentum')),
                ('kategoria', models.CharField(max_length=244, verbose_name='kategória')),
                ('megjegyzes', models.CharField(blank=True, max_length=500, verbose_name='megjegyzés')),
                ('statusz', models.CharField(choices=[('Lektorálás alatt', 'Lektorálás alatt'), ('Tördelés alatt', 'Tördelés alatt'), ('Publikus', 'Publikus')], default='Lektorálás alatt', max_length=20, verbose_name='státusz')),
            ],
            options={
                'verbose_name': 'Publikálatlan cikk',
                'verbose_name_plural': 'Publikálatlan cikkek',
            },
        ),
        migrations.CreateModel(
            name='Pozicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255, verbose_name='név')),
            ],
            options={
                'verbose_name': 'Pozíció',
                'verbose_name_plural': 'Pozíciók',
            },
        ),
        migrations.CreateModel(
            name='Tagozat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255, verbose_name='név')),
                ('betu', models.CharField(max_length=1, verbose_name='betűjel')),
            ],
            options={
                'verbose_name': 'Tagozat',
                'verbose_name_plural': 'Tagozatok',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilkep', models.ImageField(blank=True, upload_to='', verbose_name='profilkép')),
                ('evfolyam', models.CharField(blank=True, choices=[('KNY', 'KNY'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=3, verbose_name='évfolyam')),
                ('pozicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delesE.pozicio')),
                ('tagozat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delesE.tagozat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profilok',
            },
        ),
    ]
