# Generated by Django 4.0.3 on 2022-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delesE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcikk',
            name='dokumentum',
            field=models.FileField(upload_to='documents/', verbose_name='dokumentum'),
        ),
        migrations.AlterField(
            model_name='edcikk',
            name='statusz',
            field=models.CharField(choices=[('Lektorálás alatt', 'Lektorálás alatt'), ('Tördelés alatt', 'Tördelés alatt'), ('Visszaküldve', 'Visszaküldve'), ('Publikus', 'Publikus')], default='Lektorálás alatt', max_length=20, verbose_name='státusz'),
        ),
    ]
