# Generated by Django 4.0.3 on 2022-05-11 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delesE', '0003_edcikk_szerzo_alter_edcikk_dokumentum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edcikk',
            name='szerzo',
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
