# Generated by Django 4.0.3 on 2022-04-02 19:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delesE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255, verbose_name='név')),
            ],
            options={
                'verbose_name': 'Kategória',
                'verbose_name_plural': 'Kategóriák',
            },
        ),
        migrations.CreateModel(
            name='Cikk',
            fields=[
                ('cim', models.CharField(max_length=255, verbose_name='cím')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='id')),
                ('rovtartalom', models.CharField(max_length=510, verbose_name='rövtartalom')),
                ('tartalom', ckeditor.fields.RichTextField(verbose_name='tartalom')),
                ('datum', models.DateField(auto_now_add=True, verbose_name='dátum')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delesU.kategoria')),
                ('szerzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delesE.profil')),
            ],
            options={
                'verbose_name': 'Cikk',
                'verbose_name_plural': 'Cikkek',
            },
        ),
    ]
