# Generated by Django 4.0.3 on 2022-04-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delesU', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cikk',
        ),
    ]
