# Generated by Django 4.0.3 on 2022-04-02 19:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delesE', '0001_initial'),
        ('delesU', '0002_delete_cikk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cikk',
            fields=[
                ('cim', models.CharField(max_length=255, verbose_name='cím')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='id')),
                ('rovtartalom', models.CharField(max_length=510, verbose_name='rövtartalom')),
                ('tartalom', ckeditor.fields.RichTextField(verbose_name='tartalom')),
                ('datum', models.DateField(auto_now_add=True, verbose_name='dátum')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delesU.kategoria')),
                ('szerzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delesE.profil')),
            ],
            options={
                'verbose_name': 'Cikk',
                'verbose_name_plural': 'Cikkek',
            },
        ),
    ]
