# Generated by Django 4.0.3 on 2022-04-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delesU', '0003_cikk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cikk',
            name='kategoria',
        ),
        migrations.DeleteModel(
            name='Kategoria',
        ),
    ]
