# Generated by Django 4.0.3 on 2022-04-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delesU', '0005_kategoria_cikk_kategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoria',
            name='rov',
            field=models.CharField(default='i', max_length=100, verbose_name='röv'),
            preserve_default=False,
        ),
    ]
