# Generated by Django 4.0.3 on 2022-04-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delesU', '0009_alter_cikk_alkat1_alter_cikk_alkat2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoria',
            name='rov',
        ),
        migrations.AddField(
            model_name='kategoria',
            name='slug',
            field=models.SlugField(default='ad', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cikk',
            name='alkat1',
            field=models.CharField(blank=True, choices=[('fontos', 'Fontos'), ('legfontosabb', 'Legfontosabb'), ('friss', 'Friss')], max_length=20, verbose_name='alkategória 1'),
        ),
        migrations.AlterField(
            model_name='cikk',
            name='alkat2',
            field=models.CharField(blank=True, choices=[('fontos', 'Fontos'), ('legfontosabb', 'Legfontosabb'), ('friss', 'Friss')], max_length=20, verbose_name='alkategória 2'),
        ),
        migrations.AlterField(
            model_name='cikk',
            name='alkat3',
            field=models.CharField(blank=True, choices=[('fontos', 'Fontos'), ('legfontosabb', 'Legfontosabb'), ('friss', 'Friss')], max_length=20, verbose_name='alkategória 3'),
        ),
    ]
