# Generated by Django 4.0.3 on 2022-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delesU', '0010_remove_kategoria_rov_kategoria_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cikk',
            name='alkat1',
            field=models.CharField(blank=True, choices=[('legfontosabb', 'Legfontosabb'), ('friss', 'Friss'), ('fontos', 'Fontos')], max_length=20, verbose_name='alkategória 1'),
        ),
        migrations.AlterField(
            model_name='cikk',
            name='alkat2',
            field=models.CharField(blank=True, choices=[('legfontosabb', 'Legfontosabb'), ('friss', 'Friss'), ('fontos', 'Fontos')], max_length=20, verbose_name='alkategória 2'),
        ),
        migrations.AlterField(
            model_name='cikk',
            name='alkat3',
            field=models.CharField(blank=True, choices=[('legfontosabb', 'Legfontosabb'), ('friss', 'Friss'), ('fontos', 'Fontos')], max_length=20, verbose_name='alkategória 3'),
        ),
    ]
